### ISSUE TITLE
Add info on using pre-built locales in README

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-intl#35]
Can be copied from http://www.telerik.com/kendo-angular-ui/components/internationalization/#toc-load-pre-built-data

/cc @danielkaradachki

**Comment by danielkaradachki** [comment]
Actually, it cannot. The kendo-intl package does not provide pre-built data. Only task to generate it.

**Comment by tsvetomir** [comment]
Silly me, I forgot that we only generate locales in the Angular package. Disregard.
