### ISSUE TITLE
Question about `formatNumber(Infinity)`

### ISSUE THREAD

**Issue by Xizario** [telerik/kendo-intl#41]
Currently the `formatNumber` called with `Infinity` or `NaN` returns the [original value](https://github.com/telerik/kendo-intl/blob/58a0fe429d4b031d9626d3ce2b364bdd381c9730/src/numbers/format-number.js#L12).

But in the [ts definitions](https://github.com/telerik/kendo-intl/blob/58a0fe429d4b031d9626d3ce2b364bdd381c9730/src/numbers.d.ts#L68) it is said that the method should return string.

Currently I will check my values before passing them to the method, to avoid stepping into this case. But it will be good to know if we are planing to change the method or the definitions in future.

**Comment by ipeshev** [comment]
fixed in 1.3.0-dev.201710031120
