### ISSUE TITLE
Load Persian calender if locale is set to fa

### ISSUE THREAD

**Issue by ahmadalli** [telerik/kendo-intl#45]
currently, I'm trying kendo angular and I'm facing a problem with `fa` localization. we can find [persian calendar definitions](https://github.com/unicode-cldr/cldr-cal-persian-modern) in CLDR database but I don't know how can I make kendo intl to use that calendar instead of Georgian calendar.

**Comment by danielkaradachki** [comment]
Using calendars other than the Gregorian is not currently supported.
