### ISSUE TITLE
Better default options value

### ISSUE THREAD

**Issue by meriturva** [telerik/kendo-intl#56]
On line:

https://github.com/telerik/kendo-intl/blob/develop/src/numbers/format-number.js#L21

Code just checks if options is null or not:

```
if (options) {
        const style = (options || {}).style || DECIMAL;
        result = standardNumberFormat(number, Object.assign({}, info.numbers[style], options), info);
    } 
```

i guess `options || {}` is not useful anymore so:

```
if (options) {
        const style = options.style || DECIMAL;
        result = standardNumberFormat(number, Object.assign({}, info.numbers[style], options), info);
    } 
```

**Comment by danielkaradachki** [comment]
Indeed, the check is not necessary. Could you clarify what problems is it causing?

**Comment by meriturva** [comment]
No problem at all in our case....

i was just looking for default value related to: https://github.com/telerik/kendo-angular/issues/1812
that you already answer (thanks).

My tip is just a code improvement.
