### ISSUE TITLE
Error: NoLocale: Missing locale info for 'de'

### ISSUE THREAD

**Issue by AndreiF13** [telerik/kendo-intl#66]
Hi,
there is a error on refresh a component that has a DatePicker element
`Error: NoLocale: Missing locale info for 'de'
    error errors.js:39
    localeInfo info.js:60
    splitDateFormat split-date-format.js:57
    splitDateFormat IntlService.js:137
    allFormatedMonths kendo-date.js:371
    KendoDate kendo-date.js:37
    render DateInput.js:240
    React 15
    retryTimedOutBoundary (index):1075
    wrapped scheduler-tracing.development.js:177`

Please let me know a hotfix.
Thank you!

**Comment by danielkaradachki** [comment]
If you are having problem with using the intl API with particular components please open issue in the corresponding repo with more detailed information and a runnable sample that demonstrates it.  For the Kendo React components, please open an issue in [this](https://github.com/telerik/kendo-react/issues ) repository.
