### ISSUE TITLE
Translation for sorting asc / desc is not working

### ISSUE THREAD

**Issue by AndreiF13** [telerik/kendo-intl#74]
Hi,
translation for sorting (Sort Ascending / Sort Descending) is not working in column menu. (React UI)
Please check.
Thank you.

**Comment by danielkaradachki** [comment]
The issue tracker is for problems regarding the kendo-intl package. For issues regarding the React components, please open an issue with more detailed information in the [kendo-react](https://github.com/telerik/kendo-react/issues) repo.

**Comment by AndreiF13** [comment]
it is a intl issue
import { LocalizationProvider, IntlProvider } from '@progress/kendo-react-intl'
