### ISSUE TITLE
Capital "A" specifier for custom date formatting

### ISSUE THREAD

**Issue by peebeebee** [telerik/kendo-intl#75]
Hi,
Would it be possible to also add a capital 'A' as a synonym for 'a' specifier, which renders the day period.
https://github.com/telerik/kendo-intl/blob/master/docs/date-formatting/index.md#custom

This way your formatting is more similar to other libraries.

**Comment by danielkaradachki** [comment]
Hi, 

Shouldn't be much trouble to implement but the format specifiers are taken from the CLDR specifications and there is already a capital 'A' specifier that is not used for day period:

http://www.unicode.org/reports/tr35/tr35-dates.html#dfst-second

The kendo-intl does not support it yet it may be necessary some day. Therefore I don't think that we should it as alias.

**Comment by peebeebee** [comment]
Aah, thanks for the information!
